## List of colors usable for each cell
COLORS = [
'white',
'brown4',
'gray9',
'dark orange',
'bisque2',
'DarkOliveGreen4',
'VioletRed3',
'maroon',
'gray16',
'LightBlue2',
'medium turquoise',
'thistle4',
'light steel blue',
'DarkOrchid2',
'gray25',
'sienna1',
'chartreuse2',
'DarkSlateGray4',
'khaki1',
'gray60',
'SkyBlue4',
'firebrick2',
'gray45',
'olive drab',
'forest green',
'gray78',
'PaleGreen2',
'gray4',
'turquoise1',
'seashell2',
'gray46',
'snow3',
'firebrick4',
'indian red',
'turquoise2',
'steel blue',
'gray39',
'dark orchid',
'dark turquoise',
'dark salmon',
'AntiqueWhite4',
'RosyBrown1',
'gray91',
'pink1',
'gold4',
'plum1',
'cyan',
'SeaGreen2',
'DarkOliveGreen1',
'orange',
'DodgerBlue2',
'gray59',
'tomato2',
'DarkOrange2',
'MistyRose4',
'blue2',
'gray86',
'cyan2',
'LavenderBlush3',
'blanched almond',
'LightSalmon2',
'gray70',
'LightPink2',
'gray20',
'cornflower blue',
'maroon2',
'light cyan',
'gray89',
'cyan4',
'gray69',
'LightYellow4',
'gray90',
'salmon',
'dark olive green',
'azure3',
'wheat3',
'wheat4',
'red4',
'medium orchid',
'gray76',
'pink',
'navy',
'powder blue',
'MediumOrchid3',
'medium sea green',
'LightSteelBlue4',
'LightSteelBlue3',
'salmon3',
'OrangeRed2',
'gray64',
'light coral',
'RoyalBlue1',
'gray1',
'RosyBrown3',
'light yellow',
'LemonChiffon2',
'DarkGoldenrod1',
'LightPink3',
'IndianRed1',
'honeydew3',
'gray77',
'tan2',
'gray29',
'tomato4',
'light salmon',
'yellow2',
'yellow',
'LightCyan4',
'DeepSkyBlue3',
'blue violet',
'seashell4',
'LightSkyBlue1',
'sandy brown',
'light goldenrod yellow',
'light pink',
'saddle brown',
'gray97',
'OliveDrab4',
'DarkGoldenrod2',
'sky blue',
'DarkOrchid3',
'CadetBlue1',
'DarkSeaGreen2',
'gray67',
'khaki2',
'orange red',
'gray72',
'lawn green',
'gray',
'SkyBlue2',
'azure2',
'gray74',
'PaleTurquoise3',
'gray32',
'cyan3',
'turquoise4',
'gray36',
'RosyBrown4',
'MediumPurple3',
'coral1',
'LightBlue3',
'PeachPuff2',
'gray19',
'DarkOliveGreen3',
'medium blue',
'rosy brown',
'RoyalBlue4',
'IndianRed4',
'gray82',
'maroon1',
'tan4',
'red3',
'gray54',
'gray80',
'gray12',
'gray30',
'dark khaki',
'SteelBlue1',
'SlateBlue2',
'light sea green',
'SlateGray4',
'ivory4',
'aquamarine2',
'purple1',
'dark goldenrod',
'SpringGreen2',
'DeepSkyBlue2',
'salmon4',
'slate blue',
'SeaGreen3',
'chartreuse4',
'light slate gray',
'DodgerBlue3',
'yellow green',
'goldenrod4',
'gray31',
'honeydew4',
'gray55',
'gray3',
'LightGoldenrod3',
'IndianRed2',
'LightCyan3',
'DarkOliveGreen2',
'gray65',
'gray35',
'sienna4',
'gray95',
'gray10',
'brown3',
'PaleVioletRed3',
'tomato',
'LightPink1',
'PaleTurquoise4',
'gray48',
'firebrick1',
'aquamarine4',
'PaleGreen4',
'gray8',
'medium purple',
'MistyRose2',
'gray14',
'purple4',
'pale goldenrod',
'lime green',
'gray40',
'LightSalmon4',
'OliveDrab1',
'dim gray',
'gray5',
'AntiqueWhite1',
'chartreuse3',
'LightCyan2',
'coral4',
'gray75',
'light grey',
'DeepPink2',
'salmon1',
'DodgerBlue4',
'chocolate3',
'dark sea green',
'turquoise3',
'RoyalBlue2',
'gray17',
'green2',
'snow4',
'red',
'SlateGray1',
'slate gray',
'LightBlue1',
'MediumPurple2',
'gray26',
'peach puff',
'burlywood4',
'burlywood2',
'gray73',
'gray56',
'snow2',
'HotPink4',
'SlateBlue1',
'gray23',
'gray13',
'lavender blush',
'gray99',
'IndianRed3',
'pink2',
'thistle3',
'deep pink',
'aquamarine',
'orchid4',
'SlateBlue3',
'magenta3',
'DarkGoldenrod3',
'orange4',
'blue',
'tomato3',
'PaleVioletRed2',
'SkyBlue1',
'LightSkyBlue2',
'firebrick3',
'gray21',
'gray94',
'LightSalmon3',
'SeaGreen1',
'gray68',
'goldenrod3',
'OrangeRed4',
'gray66',
'bisque3',
'burlywood1',
'MediumOrchid2',
'gray15',
'gray84',
'thistle',
'green3',
'gray43',
'yellow4',
'dark green',
'purple3',
'medium violet red',
'azure',
'LightGoldenrod2',
'DarkOrchid4',
'MediumOrchid4',
'SpringGreen3',
'red2',
'DarkGoldenrod4',
'gray58',
'green yellow',
'gray71',
'SlateBlue4',
'gray63',
'LightGoldenrod4',
'dark slate gray',
'gray49',
'gray79',
'khaki',
'gray44',
'coral',
'medium spring green',
'CadetBlue2',
'DarkSeaGreen3',
'wheat2',
'gray2',
'purple2',
'coral2',
'goldenrod1',
'ivory2',
'PaleVioletRed1',
'OrangeRed3',
'gray42',
'gray47',
'goldenrod2',
'MediumPurple1',
'SlateGray3',
'SteelBlue4',
'hot pink',
'VioletRed1',
'gold2',
'magenta2',
'PaleTurquoise1',
'DeepPink4',
'gray34',
'DarkSeaGreen1',
'orchid2',
'HotPink3',
'goldenrod',
'NavajoWhite2',
'gray11',
'DarkOrange4',
'gray28',
'lemon chiffon',
'pink4',
'dark slate blue',
'RosyBrown2',
'gray37',
'LightBlue4',
'LightYellow3',
'seashell3',
'gray51',
'gray93',
'salmon2',
'SkyBlue3',
'lavender',
'SlateGray2',
'thistle1',
'gray83',
'PaleGreen1',
'CadetBlue4',
'mint cream',
'DarkSlateGray2',
'honeydew2',
'light goldenrod',
'LightPink4',
'LightGoldenrod1',
'light sky blue',
'VioletRed4',
'yellow3',
'midnight blue',
'LightSteelBlue2',
'brown1',
'plum3',
'PaleVioletRed4',
'DarkOrange3',
'AntiqueWhite3',
'dodger blue',
'green4',
'pale violet red',
'tan1',
'gray33',
'pale turquoise',
'DeepPink3',
'light slate blue',
'orange2',
'gray92',
'spring green',
'gray57',
'dark violet',
'gray81',
'sienna3',
'pale green',
'DeepSkyBlue4',
'LightYellow2',
'RoyalBlue3',
'LightSkyBlue3',
'LemonChiffon3',
'chocolate1',
'orchid1',
'HotPink2',
'cornsilk3',
'alice blue',
'MediumPurple4',
'gray52',
'gray88',
'khaki4',
'gray50',
'gray62',
'PaleGreen3',
'gray87',
'gray24',
'gray98',
'DarkSlateGray3',
'DarkOrchid1',
'MistyRose3',
'orchid3',
'HotPink1',
'AntiqueWhite2',
'gray53',
'deep sky blue',
'gray38',
'gray61',
'LemonChiffon4',
'thistle2',
'sea green',
'misty rose',
'maroon4',
'gray27',
'pink3',
'medium aquamarine',
'cornsilk4',
'chocolate2',
'royal blue',
'medium slate blue',
'maroon3',
'gray22',
'plum2',
'LightSkyBlue4',
'plum4',
'ivory3',
'blue4',
'PeachPuff3',
'PaleTurquoise2',
'gray85',
'bisque4',
'SteelBlue2',
'turquoise',
'coral3',
'papaya whip',
'bisque',
'sienna2',
'PeachPuff4',
'light blue',
'gray18',
'cadet blue',
'cornsilk2',
'NavajoWhite3',
'LightSteelBlue1',
'SteelBlue3',
'LavenderBlush4',
'azure4',
'brown2',
'DarkSeaGreen4',
'orange3',
'wheat1',
'NavajoWhite4',
'gold',
'burlywood3',
'gold3',
'MediumOrchid1',
'SpringGreen4',
'VioletRed2',
'khaki3',
'purple',
'DarkSlateGray1',
'violet red',
'gray7',
'DarkOrange1',
'LavenderBlush2',
'magenta4',
'OliveDrab2',
'CadetBlue3',
'gray6'
 ]